#!/bin/sh

x="Screenshot copied to clipboard"
name="shot_$(date '+%y%m%d_%H-%M-%S')"

hyprpicker -r -z &
sleep 0.1

[ "$*" = "fullsave" ] && grim $HOME/pix/ss/$name.png && wl-copy < $HOME/pix/ss/$name.png && notify-send -i $HOME/pix/ss/$name.png "Screenshot saved" "$HOME/pix/ss/$name.png"

[ "$*" = "selclip" ] && grim -g "$(slurp)" - | swappy -f -

killall hyprpicker
#notify-send "$x"
