#!/bin/zsh

alias ..='z ..'
alias cd='z'
alias ga='git add'
alias gc='git commit -m'
alias push='git push'
alias weather='curl -s "https://wttr.in/?1n"'
alias pacgraph='pacgraph --show-req-by -b "#232738" -l "#9778d3" -t "#cca9c6" -d "#b8d0eb"'
alias grep='grep --color=auto'
alias wget='aria2c -x 16 -s 16'
alias yarn="yarn --use-yarnrc $XDG_CONFIG_HOME/yarn/config"
alias diff='diff --color=auto'
alias df='duf -hide special'
alias neofetch="fastfetch"
alias cat="bat --paging=never"
alias less="bat --paging=always"
alias x='exit'
alias dir='dir --color=auto'

if [ "$TERM" = "linux" ] ; then
        alias ls='/bin/ls --color=auto'
else
        alias ls='eza --icons'
        alias ll='eza -lgh --icons'
        alias la='eza -lagh --icons'
fi

# Confirmations
alias ln='ln -i'

# Package Management
alias install="paru -Slq | fzf --multi --preview 'paru -Si {1}' | xargs -ro paru -S"
alias uninstall="paru -Qq | fzf --multi --preview 'paru -Qi {1}' | xargs -ro paru -Rcns"
alias update="paru -Syu --noconfirm"
#alias garbage="paru -Rcns $(paru -Qqdtt)"
