#!/bin/sh

###########################################################################################
# NOTE: you need to be member of "video" group or maybe "input" group for this to work... #
###########################################################################################

# dir where the backlight component resides..
root_dir="/sys/class/backlight"

#########################################################################
# brighness directory can be different per device, check above root_dir #
#########################################################################
#for intel
backlight_dir="intel_backlight"

#for acpi (generic)
#backlight_dir="acpi_backlight0"

#for amd
#backlight_dir="amdgpu_bl1"

#file read
brightness_file="$root_dir/$backlight_dir/brightness"
current=$(cat "$brightness_file")
max=$(cat "$root_dir/$backlight_dir/max_brightness")
                               
#runtime
increment=${2:-5} #default it will add 5, which is around 2% brightness

case $1 in
    +) new=$((current + increment)) ;;
    -) new=$((current - increment)) ;;
    *) printf "Unknown Operator, use only + or -\n" && exit 1 ;;
esac

[ "$new" -ge "$max" ] && new=$max
[ "$new" -le 0 ] && new=0
printf '%s' "$new" > "$brightness_file"

#shellcheck disable=SC2004
notify-send -i "lol" "☀️  $((${new}00/${max}))" -t 1000 -h "string:x-canonical-private-synchronous:${0##*/}"
